### ISSUE TITLE
Integrating the database

### ISSUE THREAD

**Issue by itsgoofer** [terlici/base-express#1]
That's a very interesting structure, but I'm actually wondering how could a model be used alongside a module like Sequelize as in passing the actual Sequelize database instance to the model. 
Any ideas?

**Comment by fidanov** [comment]
You would need one more file usually, in your root directory you can add `db.js` file which will actually export two methods. One to connect to the database and one to return the already connected object. You can see an example with Mongo and a full tutorial here http://www.terlici.com/2015/04/03/mongodb-node-express.html

In the case of Sequelize it should probably be something like this

``` js
var MongoClient = require('mongodb').MongoClient

var state = {
  sequelize: null,
}

// url in the form of 'postgres://user:pass@example.com:5432/dbname' for example
exports.connect = function(url, done) {
  if (state.sequelize) return done()

  state.sequelize = new Sequelize(url)
  done()
}

exports.get = function() {
  return state.sequelize
}
```

Then in your model you will request this the `db.js` file from above and use it's get function to get an already configured object to create your stuff.
